### ISSUE TITLE
Zack's Lua Multimark Mod breaks S3LightFixes

### ISSUE THREAD

**Issue by TaxAkla** [magicaldave/S3LightFixes#1]
When this mod is on the list S3LightFixes can't create any patch.
Tested with version 0.1.3

https://www.nexusmods.com/morrowind/mods/53260
![Captura de tela de 2024-12-15 10-36-48](https://github.com/user-attachments/assets/16abb730-19f0-42c7-81f5-ca18c7f777fd)

**Comment by magicaldave** [comment]
Yeah, I know, I made the LUAL records in this plugin that break it.

The underlying tes3 library does not support LUAL records yet, causing this.

However, it should still generate the patch:
```rs

        let mut plugin = match Plugin::from_path(plugin_path) {
            Ok(plugin) => plugin,
            Err(e) => {
                eprintln!("{} {} {}", PLUGIN_LOAD_FAILED_ERR, plugin_path.display(), e);
                continue;
            }
        };
```
Plugins which fail to load are simply skipped during the build.

You're probably expecting it to give you some or another kind of output which it most certainly does not. Check $HOME/.local/share/openmw/data/ to find the plugin.

**Comment by TaxAkla** [comment]
Found it. I was expecting the patch being in the same path of the program like WazaLightFixes does.
Thank you for clarify.

**Comment by magicaldave** [comment]
> Found it. I was expecting the patch being in the same path of the program like WazaLightFixes does. Thank you for clarify.

No worries!
You can specify the directory it outputs to using the `OPENMW_OVERRIDE_DIR` environment variable. Like this:
```
OPENMW_OVERRIDE_DIR="$(pwd)" ./s3lightfixes
```
